### ISSUE TITLE
Remove additional sentence about contacting support

### ISSUE THREAD

**Issue by quis** [alphagov/notifications-tech-docs#23]
Introduced here: https://github.com/alphagov/notifications-tech-docs/pull/22

Can be removed when this issue is resolved: https://github.com/alphagov/tech-docs-template/issues/148

**Comment by klssmith** [comment]
The additional sentence was removed in https://github.com/alphagov/notifications-tech-docs/pull/27 and the layout looks fine - the tables are all appearing where they should in the docs, so let's close this for now.
